/* /easyclass/quizzes-data.js
   Banco de perguntas dos quizzes de professor.
   3 matérias x 3 quizzes x 20 perguntas cada = 180 perguntas.

   v2: Português e Inglês agora também têm gabarito e são corrigidos na
   hora, igual Matemática. As perguntas originais que pediam redação livre
   ("escreva um parágrafo...", "explique...") foram reformuladas em
   perguntas de resposta curta/objetiva (verdadeiro-ou-falso, identificação,
   tradução, correção de frase) para terem uma resposta certa/errada clara.

   accept = lista de respostas aceitas, comparadas de forma "solta": sem
   espaço, minúsculo, sem acento/símbolo (ver normalizeAnswer em app.js).
   Basta a resposta do usuário CONTER uma das opções da lista.
*/

const QUIZ_DATA = {
  matematica: {
    label: "Matemática",
    autoGrade: true,
    quizzes: [
      // ---- Matemática · Quiz 1 ----
      { questions: [
        { q: "Calcule: 348 + 579.", accept: ["927"] },
        { q: "Calcule: 7/8 − 1/4.", accept: ["5/8"] },
        { q: "Um produto custa R$240 e recebeu 15% de desconto. Qual é o preço final?", accept: ["204"] },
        { q: "Resolva: 3x + 7 = 28.", accept: ["7"] },
        { q: "Calcule a área de um retângulo de 12 cm por 7 cm.", accept: ["84"] },
        { q: "Simplifique a fração 45/60.", accept: ["3/4"] },
        { q: "Uma turma tem 18 meninos e 12 meninas. Qual porcentagem da turma é formada por meninas?", accept: ["40"] },
        { q: "Resolva: 2(x − 3) = 18.", accept: ["12"] },
        { q: "Calcule √225.", accept: ["15"] },
        { q: "Resolva o sistema: x + y = 10 e x − y = 2.", accept: ["x=6y=4", "6e4", "4e6"] },
        { q: "Um triângulo retângulo tem catetos 6 cm e 8 cm. Qual é a hipotenusa?", accept: ["10"] },
        { q: "Resolva: x² − 5x + 6 = 0.", accept: ["2e3", "3e2", "x=2oux=3"] },
        { q: "Determine o 15º termo da PA: 3, 7, 11, 15…", accept: ["59"] },
        { q: "Calcule: log₂ 32.", accept: ["5"] },
        { q: "Para f(x) = 3x − 4, determine f(6).", accept: ["14"] },
        { q: "Uma urna possui 4 bolas vermelhas e 6 azuis. Qual a probabilidade de retirar uma vermelha?", accept: ["2/5"] },
        { q: "Determine a distância entre A(1,2) e B(4,6).", accept: ["5"] },
        { q: "Determine a equação da reta que passa por (0,3) e (2,7).", accept: ["y=2x+3"] },
        { q: "Resolva: 2ˣ = 64.", accept: ["6"] },
        { q: "Calcule a derivada de f(x) = x³ + 2x.", accept: ["3x^2+2", "3x²+2"] },
      ]},
      // ---- Matemática · Quiz 2 ----
      { questions: [
        { q: "Calcule: 825 − 367.", accept: ["458"] },
        { q: "Calcule: 3/5 + 7/10.", accept: ["13/10"] },
        { q: "Um salário de R$2.000 recebeu aumento de 12%. Qual o novo salário?", accept: ["2240"] },
        { q: "Resolva: 5x − 9 = 36.", accept: ["9"] },
        { q: "Qual é o perímetro de um quadrado de lado 9 cm?", accept: ["36"] },
        { q: "Calcule 2³ × 2⁴.", accept: ["128"] },
        { q: "Uma viagem de 360 km foi realizada em 4 horas. Qual foi a velocidade média?", accept: ["90"] },
        { q: "Resolva: 4(x + 2) = 32.", accept: ["6"] },
        { q: "Fatore: x² − 16.", accept: ["x-4", "x+4"] },
        { q: "Resolva: x² − 8x + 15 = 0.", accept: ["3e5", "5e3", "x=3oux=5"] },
        { q: "Um círculo possui raio 4 cm. Calcule sua área usando π = 3,14.", accept: ["50.24", "50,24"] },
        { q: "Resolva o sistema: 2x + y = 11 e x − y = 1.", accept: ["x=4y=3", "4e3", "3e4"] },
        { q: "Determine o 20º termo da PA: 5, 8, 11, 14…", accept: ["62"] },
        { q: "Determine o 6º termo da PG: 2, 6, 18, 54…", accept: ["486"] },
        { q: "Resolva: log₃(x) = 4.", accept: ["81"] },
        { q: "Calcule sen 30° + cos 60°.", accept: ["1"] },
        { q: "Calcule a distância entre A(−2,1) e B(4,9).", accept: ["10"] },
        { q: "Quantas maneiras diferentes 4 pessoas podem sentar-se em 4 cadeiras enfileiradas?", accept: ["24"] },
        { q: "Resolva: 3ˣ = 81.", accept: ["4"] },
        { q: "Calcule ∫(4x + 2)dx.", accept: ["2x^2+2x", "2x²+2x"] },
      ]},
      // ---- Matemática · Quiz 3 ----
      { questions: [
        { q: "Calcule: 1.250 ÷ 25.", accept: ["50"] },
        { q: "Calcule: 5/6 × 3/10.", accept: ["1/4"] },
        { q: "Uma camisa de R$150 aumentou 20%. Qual é o novo preço?", accept: ["180"] },
        { q: "Resolva: 7x + 3 = 45.", accept: ["6"] },
        { q: "Um triângulo tem base 10 cm e altura 8 cm. Qual sua área?", accept: ["40"] },
        { q: "Transforme 2,75 metros em centímetros.", accept: ["275"] },
        { q: "A média de 6, 8, 10 e 16 é quanto?", accept: ["10"] },
        { q: "Resolva: 3(x − 5) = 21.", accept: ["12"] },
        { q: "Simplifique √72.", accept: ["6√2", "6raiz2"] },
        { q: "Resolva: x² − 10x + 21 = 0.", accept: ["3e7", "7e3", "x=3oux=7"] },
        { q: "Fatore: x² + 7x + 12.", accept: ["x+3", "x+4"] },
        { q: "Resolva o sistema: 3x + y = 14 e x − y = 2.", accept: ["x=4y=2", "4e2", "2e4"] },
        { q: "Determine a soma dos 10 primeiros termos da PA 2, 5, 8, 11…", accept: ["155"] },
        { q: "Determine o 7º termo da PG 3, 6, 12, 24…", accept: ["192"] },
        { q: "Resolva: 5ˣ = 125.", accept: ["3"] },
        { q: "Para f(x) = x² − 3x, calcule f(5).", accept: ["10"] },
        { q: "Calcule a distância entre A(0,0) e B(6,8).", accept: ["10"] },
        { q: "Em um grupo de 12 pessoas, de quantas maneiras é possível escolher 2 pessoas?", accept: ["66"] },
        { q: "Resolva: log₅(x) = 3.", accept: ["125"] },
        { q: "Calcule a derivada de f(x) = 4x² − 7x + 1.", accept: ["8x-7"] },
      ]},
    ],
  },

  portugues: {
    label: "Português",
    autoGrade: true,
    quizzes: [
      // ---- Português · Quiz 1 ----
      { questions: [
        { q: "Identifique o sujeito: “Os estudantes organizaram a apresentação.”", accept: ["osestudantes", "estudantes"] },
        { q: "Identifique o verbo: “Mariana comprou um livro.”", accept: ["comprou"] },
        { q: "Classifique a palavra “rapidamente” quanto à classe gramatical.", accept: ["adverbio"] },
        { q: "Passe para o plural: “O aluno dedicado estudou bastante.”", accept: ["osalunosdedicadosestudarambastante"] },
        { q: "“Mas” indica oposição e “mais” indica quantidade. Qual das duas é conjunção adversativa?", accept: ["mas"] },
        { q: "Complete corretamente: “Não fui à escola _____ estava doente.”", accept: ["porque"] },
        { q: "Identifique o objeto direto: “Pedro comprou um computador novo.”", accept: ["umcomputadornovo", "computadornovo"] },
        { q: "Passe para a voz passiva: “O professor corrigiu as provas.”", accept: ["asprovasforamcorrigidaspeloprofessor"] },
        { q: "Identifique o tempo verbal de “estudaremos”.", accept: ["futurodopresente", "futuro"] },
        { q: "A expressão “dar com a língua nos dentes” significa contar um segredo ou ficar calado?", accept: ["contarumsegredo", "contarsegredo", "segredo"] },
        { q: "Identifique a figura de linguagem: “Meu coração é um deserto.”", accept: ["metafora"] },
        { q: "Em “Ela tem um coração de ouro”, o sentido é literal ou figurado (conotativo)?", accept: ["figurado", "conotativo"] },
        { q: "Classifique a oração destacada: “Quando cheguei, eles já tinham saído.” — é uma oração principal ou subordinada?", accept: ["subordinada"] },
        { q: "Uma oração subordinada tem sentido completo sozinha ou depende de outra oração?", accept: ["dependedeoutra", "dependente"] },
        { q: "Corrija: “Houveram muitos problemas na escola.”", accept: ["houvemuitosproblemasnaescola"] },
        { q: "Em “Fui à escola”, a crase aparece porque “escola” é palavra feminina que aceita artigo — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Uma propaganda tem função da linguagem apelativa (conativa) ou poética?", accept: ["apelativa", "conativa"] },
        { q: "Coesão trata das ligações entre palavras/frases, e coerência trata do sentido geral do texto — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "A educação é fundamental para o desenvolvimento de quê? Complete: “A educação amplia as _____ das pessoas.” (uma palavra: oportunidades, conhecimento ou cidadania)", accept: ["oportunidades", "conhecimento", "cidadania"] },
        { q: "O uso excessivo das redes sociais tende a (prejudicar ou melhorar) a concentração dos jovens?", accept: ["prejudicar"] },
      ]},
      // ---- Português · Quiz 2 ----
      { questions: [
        { q: "Identifique o sujeito: “As crianças brincavam no parque.”", accept: ["ascriancas", "criancas"] },
        { q: "Identifique o predicado da frase: “O professor explicou a matéria.”", accept: ["explicouamateria"] },
        { q: "Classifique “felizmente” quanto à classe gramatical.", accept: ["adverbio"] },
        { q: "Corrija: “Os aluno estudou para a prova.”", accept: ["osalunosestudaramparaaprova"] },
        { q: "Qual conjunção indica causa: “porque” ou “quando”?", accept: ["porque"] },
        { q: "Identifique o objeto indireto: “João precisava de ajuda.”", accept: ["deajuda", "ajuda"] },
        { q: "Passe para a voz ativa: “A prova foi corrigida pela professora.”", accept: ["aprofessoracorrigiuaprova"] },
        { q: "Identifique o tempo verbal de “havíamos estudado”.", accept: ["maisqueperfeito"] },
        { q: "“Chover no molhado” significa repetir algo já óbvio ou fazer algo novo?", accept: ["repetiralgojaobvio", "obvio", "repetir"] },
        { q: "Identifique a figura de linguagem: “O vento cantava entre as árvores.”", accept: ["personificacao"] },
        { q: "Metáfora compara duas coisas sem usar “como” — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Metonímia troca uma palavra por outra que tem relação de proximidade (ex: “ler Machado de Assis”) — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Classifique a oração destacada: “Embora estivesse cansado, continuou trabalhando.” — principal ou subordinada?", accept: ["subordinada"] },
        { q: "Uma oração subordinada adverbial expressa uma circunstância (tempo, causa, concessão etc.) — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Em “Entreguei o documento à diretora”, a crase aparece porque “diretora” é palavra feminina — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Um texto dissertativo-argumentativo apenas narra fatos, sem apresentar tese nem argumentos — verdadeiro ou falso?", accept: ["falso"] },
        { q: "O narrador-personagem participa da história e o narrador-observador apenas observa — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Intertextualidade é o diálogo entre diferentes textos — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "A desigualdade social está diretamente ligada à distribuição desigual de quê? (renda ou oportunidades)", accept: ["renda", "oportunidades"] },
        { q: "A leitura contribui para (ampliar ou reduzir) o vocabulário e o repertório cultural?", accept: ["ampliar"] },
      ]},
      // ---- Português · Quiz 3 ----
      { questions: [
        { q: "Identifique o núcleo do sujeito: “Os três melhores alunos venceram.”", accept: ["alunos"] },
        { q: "Classifique o predicado: “Maria permaneceu tranquila.” — nominal ou verbal?", accept: ["nominal"] },
        { q: "Sujeito composto tem apenas um núcleo, e sujeito simples tem vários núcleos — verdadeiro ou falso?", accept: ["falso"] },
        { q: "Corrija: “Fazem dois anos que não o vejo.”", accept: ["fazdoisanosquenaoovejo"] },
        { q: "Regência verbal trata da relação do verbo com seus complementos, e regência nominal trata de nomes com seus complementos — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "No sentido de “ver”, o verbo “assistir” pede a preposição “a” — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Em “Ele se referiu à professora”, a crase aparece porque “referir-se” pede a preposição “a” mais o artigo feminino — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Classifique a oração destacada: “O aluno que estudou passou.” — é adjetiva ou substantiva?", accept: ["adjetiva"] },
        { q: "Oração subordinada substantiva funciona como adjetivo, e a adjetiva funciona como substantivo — verdadeiro ou falso?", accept: ["falso"] },
        { q: "Ambiguidade ocorre quando uma frase permite mais de uma interpretação — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "A comparação usa conectivo (como/tal qual) e a metáfora não usa — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Denotação é o sentido literal e conotação é o sentido figurado — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Polissemia é quando uma palavra tem vários significados — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Coesão textual trata das conexões gramaticais entre as partes do texto — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Coerência textual trata da lógica e do sentido geral do texto — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "O Realismo brasileiro critica a sociedade e valoriza a objetividade — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "O Modernismo brasileiro valoriza a liberdade formal e a linguagem coloquial — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "Machado de Assis é considerado um dos maiores autores da literatura brasileira — verdadeiro ou falso?", accept: ["verdadeiro"] },
        { q: "A desigualdade educacional está ligada ao acesso desigual a quê? (escolas de qualidade ou recursos)", accept: ["acesso", "escolas", "recursos"] },
        { q: "Um texto argumentativo defende uma tese ou apenas narra uma história?", accept: ["tese"] },
      ]},
    ],
  },

  ingles: {
    label: "Inglês",
    autoGrade: true,
    quizzes: [
      // ---- English · Quiz 1 ----
      { questions: [
        { q: "Traduza: “I am a student.”", accept: ["eusouumestudante", "eusouestudante"] },
        { q: "Passe para a negativa: “She likes music.”", accept: ["shedoesnotlikemusic", "shedoesntlikemusic"] },
        { q: "Passe para a interrogativa: “They play soccer.”", accept: ["dotheyplaysoccer"] },
        { q: "Complete: “He _____ two brothers.”", accept: ["has"] },
        { q: "Complete: “We _____ Brazilian.”", accept: ["are"] },
        { q: "Passe para o passado: “I study English.”", accept: ["istudiedenglish"] },
        { q: "Traduza: “She went to school yesterday.”", accept: ["elafoiparaaescolaontem", "elafoiaescolaontem"] },
        { q: "Complete com “some” ou “any”: “I have _____ friends here.”", accept: ["some"] },
        { q: "Escreva o plural de “child”.", accept: ["children"] },
        { q: "Escreva o comparativo de “good”.", accept: ["better"] },
        { q: "Escreva o superlativo de “bad”.", accept: ["worst"] },
        { q: "Complete: “There _____ three books on the table.”", accept: ["are"] },
        { q: "Identifique o tempo verbal: “They are watching TV.”", accept: ["presentcontinuous", "presentecontinuo"] },
        { q: "Identifique o tempo verbal: “He had finished the work.”", accept: ["pastperfect", "maisqueperfeito"] },
        { q: "Traduza: “I have lived here for five years.”", accept: ["eumoroaquihacincoanos"] },
        { q: "“Much” é usado para incontáveis e “many” para contáveis — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "Complete: “If it rains tomorrow, I _____ stay home.”", accept: ["will"] },
        { q: "Traduza: “I used to play soccer when I was younger.”", accept: ["eujogavafutebolquandoeramaisjovem", "eucostumavajogarfutebolquandoeramaisjovem"] },
        { q: "Na frase “My name is ___”, o que a pessoa está apresentando?", accept: ["nome", "name"] },
        { q: "Para descrever uma rotina diária em inglês, qual tempo verbal é o mais usado: simple present ou past continuous?", accept: ["simplepresent", "presentesimples"] },
      ]},
      // ---- English · Quiz 2 ----
      { questions: [
        { q: "Traduza: “I have never been to Canada.”", accept: ["nuncafuiaocanada", "euncafuiaocanada"] },
        { q: "Passe para a negativa: “She has finished the homework.”", accept: ["shehasnotfinishedthehomework", "shehasntfinishedthehomework"] },
        { q: "Passe para a interrogativa: “They have seen this movie.”", accept: ["havetheyseenthismovie"] },
        { q: "Complete: “He _____ working since 8 a.m.”", accept: ["hasbeen"] },
        { q: "Complete: “We _____ studying English for two years.”", accept: ["havebeen"] },
        { q: "Passe para o passado: “She goes to school every day.”", accept: ["shewenttoschooleveryday"] },
        { q: "Transforme para a voz passiva: “The teacher corrected the tests.”", accept: ["thetestswerecorrectedbytheteacher"] },
        { q: "Complete: “If I had more time, I _____ travel more.”", accept: ["would"] },
        { q: "“Since” é usado com duração e “for” é usado com um ponto no tempo — verdadeiro ou falso?", accept: ["falso"] },
        { q: "“Say” não leva objeto pessoal direto e “tell” leva — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "Identifique o tempo verbal: “I had already eaten.”", accept: ["pastperfect", "maisqueperfeito"] },
        { q: "Identifique o tempo verbal: “She will have finished by tomorrow.”", accept: ["futureperfect", "futuroperfeito"] },
        { q: "Corrija: “He don’t like coffee.”", accept: ["hedoesntlikecoffee", "hedoesnotlikecoffee"] },
        { q: "Corrija: “She have two brothers.”", accept: ["shehastwobrothers"] },
        { q: "“Must” expressa obrigação forte e “should” expressa sugestão/conselho — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "Traduza: “You should have studied more.”", accept: ["vocedeveriaterestudadomais"] },
        { q: "“Give up” significa desistir ou continuar?", accept: ["desistir"] },
        { q: "Em um texto argumentativo em inglês, a ideia principal geralmente aparece na introdução ou na conclusão?", accept: ["introducao"] },
        { q: "Para descrever uma rotina com aproximadamente 80 palavras em inglês, qual tempo verbal é o mais indicado?", accept: ["simplepresent", "presentesimples"] },
        { q: "A importância de aprender inglês está mais ligada à comunicação global ou ao isolamento?", accept: ["comunicacao"] },
      ]},
      // ---- English · Quiz 3 ----
      { questions: [
        { q: "Traduza: “If I had known, I would have helped.”", accept: ["seeusoubesseeuteriaajudado"] },
        { q: "Passe para a voz passiva: “Scientists have discovered a new species.”", accept: ["anewspecieshasbeendiscoveredbyscientists"] },
        { q: "Passe para discurso indireto: “I will finish the project tomorrow”, she said.", accept: ["shesaidshewouldfinishtheprojectthenextday", "shesaidshewouldfinishtheproject"] },
        { q: "Complete: “If I had more money, I _____ travel around the world.”", accept: ["would"] },
        { q: "Complete: “By next year, they _____ here for ten years.”", accept: ["willhavelived", "willhavebeen"] },
        { q: "No second conditional a condição é sobre o passado que não aconteceu, e no third conditional a condição é hipotética/presente — verdadeiro ou falso?", accept: ["falso"] },
        { q: "“Few” tem sentido negativo (quase nenhum) e “a few” tem sentido positivo (alguns) — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "“Little” tem sentido negativo (quase nada) e “a little” tem sentido positivo (um pouco) — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "“Would rather” expressa preferência — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "Complete usando “would rather”: “I _____ stay home tonight.”", accept: ["wouldrather"] },
        { q: "“I stopped smoking” significa que a pessoa parou para fumar, e “I stopped to smoke” significa que ela parou de fumar — verdadeiro ou falso?", accept: ["falso"] },
        { q: "Corrija: “Despite of being tired, he continued working.”", accept: ["despitebeingtiredhecontinuedworking", "inspiteofbeingtiredhecontinuedworking"] },
        { q: "“Who” refere-se a pessoas, “which” a coisas e “whose” indica posse — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "Uma relative clause dá informação adicional sobre um substantivo já mencionado — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "“Give up” é um phrasal verb que significa desistir — verdadeiro ou falso?", accept: ["verdadeiro", "true"] },
        { q: "Em um texto argumentativo, a tese do autor normalmente aparece logo no início ou só no final?", accept: ["inicio"] },
        { q: "Argumentos em um texto servem para sustentar ou enfraquecer a tese defendida?", accept: ["sustentar"] },
        { q: "Ao formalizar uma frase informal, deve-se manter ou evitar gírias e contrações?", accept: ["evitar"] },
        { q: "Um texto sobre tecnologia na educação normalmente discute benefícios e desafios, ou apenas desvantagens?", accept: ["beneficios"] },
        { q: "Um texto argumentativo bem estruturado apresenta problema, causas e uma solução, ou apenas críticas?", accept: ["solucao"] },
      ]},
    ],
  },
};
